### PR TITLE
[Lab 7] Testing Strategy 

### LINKED ISSUE #381: [BE] Write Tests for News Endpoint
### Description

We have implemented an endpoint for fetching news, and tests for this endpoint should be written.

### Required Activities

- [ ] Write unit tests covering all cases

### Estimated Time

30 min

### Deadline

12 Nov 2024

### Reviewer

@cemgungor1

### LINKED ISSUE #402: Plan testing for frontend
### Description

As it stated in the Lab7's description, we should create an outline for testing of frontend.

### Required Activities

- [x] Initialize a plan
- [x] Create example tests
- [x] Commit changes made to lab branch

### Estimated Time

2 hours

### Deadline

19.11.2024

### Reviewer

@m-erkam

### PR DESCRIPTION
**Pull request by hikasap**
This PR will cover work done related to lab 7 assignments.

```
Lab 7 description of Nov 19:

•⁠  ⁠Create a PR dedicated to this lab session where you will link work done in this lab: commits, wiki pages, issues, meeting notes, etc. Start the PR with a commit in a new branch. Then, add commits to the branch, and document all the work in the PR description and comments. The commits should include co-authors, if there are any, see [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors). The description and comments should include the names of the main contributors related to the linked work. The PR should be finalized today at 8:00 PM.
•⁠  ⁠Plan for the demo next week, including data population strategy, scenario, etc.
•⁠  ⁠Outline the software quality plan, including unit test coverage and integration testing.
•⁠  ⁠Document the user experience decisions made in the previous lab.
•⁠  ⁠Individuals can work on other things related to the milestone 2 preparation, if the previous items are to be met.

```

### CODE REVIEW

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
> •⁠  ⁠Document the user experience decisions made in the previous lab.

See previous lab 6 PR #385.

**Comment by cemgungor1** [comment]
Demo scenarios are created. Can take a look at here [#400](https://github.com/bounswe/bounswe2024group2/issues/400)

**Comment by oguzpancuk** [comment]
We've decided to use [Faker](https://faker.readthedocs.io/en/master/) to generate and populate data into our system. 

Here's a plan of how to use it:

1. Define data requirements
    1. Identify the models needing dummy data and determine the relationships and constraints: (Currency, Stock, Tag, Portfolio, Post, Comment)
    2. Decide on the number of entries for each model
2. Create a new python file populate.py to write the population script
3. Modify the Docker Configuration
    1. Add latest version of Faker to requirements.txt for installation
    2. Modify the docker-compose.yml file to automate the data population during the container's startup phase. 
```
command: >  
sh -c " 
 python manage.py migrate &&  
 python manage.py shell < bounswe2024group2/backend/populate.py && 
  “
```
4. Check populate.py to ensure foreign keys are handled properly for relationships and constraints
5. Build and run the Docker Containers

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
We have created and example integration test using jest with @mahmutbugramert. See [commit](https://github.com/bounswe/bounswe2024group2/pull/399/commits/db2f83a83c1ae481c2e024021229aa42df2f894b)

**Comment by rukiyeaslan** [comment]
## Testing in Backend
Testing for backend will be managed by using unit tests and integration tests. For each endpoint that's created in the backend, unit tests and integration tests covering each success and fail scenarios to catch edge cases will be implemented.

- Tests will be placed into `test.py` file, which inherits `django.test.TestCase`.
- To run the test `python manage.py test` command will be used.

### Unit Tests

- Unit tests focus on testing individual components or functions  to ensure they work as expected in their specific context without taking other units in the project into account. 
- They are designed to validate the behavior of small, specific parts of the code, such as serializers, models, or individual methods in views, without external dependencies.

### Integration Tests

- Integration tests verify that different parts of the application work together correctly. 
- These tests cover the end-to-end functionality of features, ensuring that all components, such as views, serializers, and external services, interact as intended.

Tests for news endpoint, where news are fetched from different RSS feeds, are implemented implemented in this PR and can be found here:
- [unit tests](https://github.com/bounswe/bounswe2024group2/pull/399/commits/d3636df30fa8453694e5e053137ffac645fa9c09)
- [integration tests](https://github.com/bounswe/bounswe2024group2/pull/399/commits/c55bb6fd871a69f5e4dc982b3d1a2306080e33b3)

**Comment by m-erkam** [comment]
We decided to use Jest to test our React Native application with my teammate @furkansenkal. Also, we created tests for login and profile pages that covers rendering for both pages and logging in for login page.

**Comment by mahmutbugramert** [comment]
> We have created and example integration test using jest with @mahmutbugramert. See [commit](https://github.com/bounswe/bounswe2024group2/pull/399/commits/db2f83a83c1ae481c2e024021229aa42df2f894b)

Fixes #402

**Pull request closed without merging**
