### PR TITLE
feat: Add tags, username, and publish dates to posts.

### PR DESCRIPTION
**Pull request by mahmutbugramert**
This PR is linked to #448, and #452. All changes mentioned in the issues are made.

### CODE REVIEW

**Review by Halil-Ibrahim-Kasapoglu — CHANGES_REQUESTED** [review]
This pr changes many unrelated things and that should be resolved. I cannot merge this in this form. It should contain only your changes related to tags

**Comment by mahmutbugramert** [comment]
I am not sure what happened but when I change the base to main, only my changes appear. Can be main ahead of dev branch? If not I will try to solve the problem.

**Comment by mahmutbugramert** [comment]
> I am not sure what happened but when I change the base to main, only my changes appear. Can be main ahead of dev branch? If not I will try to solve the problem.

I found the problem. I will try to fix it.

**Comment by mahmutbugramert** [comment]
I created new PR #457. It is open to review @Halil-Ibrahim-Kasapoglu. This one can be closed.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Closing this one as it is obsolete after #457

**Pull request closed without merging**
