### PR TITLE
W3C - Annotation Standard Documentation

### PR DESCRIPTION
**Pull request by Halil-Ibrahim-Kasapoglu**
This PR will cover work done related to lab 5 assignments.

```
Lab 5 description:

- Create a PR dedicated to this lab session where you will link work done in this lab: commits, wiki pages, issues, meeting notes, etc. Start the PR with a commit in a new branch. Then, add commits to the branch, and document all the work in the PR description and comments. The commits should include co-authors, if there are any, see [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors). The description and comments should include the names of the main contributors related to the linked work. The PR should be finalized today at 8:00 PM.
- Standard selection and documentation, if you have not done so:
  - Document the standard in your wiki as to:
    1. what is it for, its benefits,
    2. what are the requirements of following the standard,
    3. how it will be enforced in practice.
- Substantial commit(s) regarding the selected standard,
- ⁠Substantial commit(s) regarding domain specificity.

```

- We need to create md file of document under docs folder named w3c-annotation.md. 
- Also we need to create a respective wiki document.

### CODE REVIEW

**Comment by cemgungor1** [comment]
This [commit](https://github.com/bounswe/bounswe2024group2/pull/372/commits/f1bbd7043dbdab8315a36b85a3b7d5b8a6d66dd1) adds benefits part of the annotation documentation which explains the benefits of w3c annotation model in our project.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Created a dedicated blank documentation page for annotation standards on the wiki. See [here](https://github.com/bounswe/bounswe2024group2/wiki/W3C%E2%80%90Annotation)
We should update the wiki content on that page once our work done.
Added that page to the sidebar on this [commit](https://github.com/bounswe/bounswe2024group2/wiki/_Sidebar/d6cda7fcaf698bfbf3a7d90e84781b4426f277eb).

**Comment by oguzpancuk** [comment]
This [commit](https://github.com/bounswe/bounswe2024group2/pull/372/commits/b461aa892676a02adcedfe40c1e00f5cdca5828f) adds requirements part of the annotation documentation which explains the requirements of w3c annotation model in our project.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
We have added frontend enforcement part to w3c annotation doc in this [commit](https://github.com/bounswe/bounswe2024group2/pull/372/commits/348afd51b700361ec8777a859dd358ccb5c2fe52)

**Comment by furkansenkal** [comment]
We have added mobile enforcement part to w3c annotation doc in this [commit](https://github.com/bounswe/bounswe2024group2/commit/a54ccdd84d219f7e5d1b8b463f46c2577d86031e).

**Pull request merged**
